import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import myContext from "@/helper/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Practice app",
  description: "Generated by Laiba",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <Header />
        <myContext>{children}</myContext>
      </body>
    </html>
  );
}
